name: Pest PHP Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  pest:

    runs-on: ubuntu-latest
    permissions:
      contents: write  # for Git to git apply

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gd, intl, pdo_mysql
          coverage: none # disable xdebug, pcov

      - name: Init database
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -h127.0.0.1 -proot -e 'create database laravel;'

      # install dependencies from composer.json
      - name: Install test dependencies
        run: composer install --prefer-dist --no-progress

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # install dependencies from package.json
      - name: Install test dependencies
        run: npm install

      # build assets
      - name: Build assets
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        run: php artisan migrate

      # run pest tests
      - name: Run Pest PHP Tests
        run: php artisan test